[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
loko_swap = "5zJ1miHbyLMqSEhZZxqQV3ECUzu6TPi1JhUSpwMFQVPh"
dynamic_fee_hook = "69VddXVhzGRGh3oU6eKoWEoNMJC8RJX6by1SgcuQfPR9"

[programs.devnet]
loko_swap = "5zJ1miHbyLMqSEhZZxqQV3ECUzu6TPi1JhUSpwMFQVPh"
dynamic_fee_hook = "69VddXVhzGRGh3oU6eKoWEoNMJC8RJX6by1SgcuQfPR9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/caballoloko/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"



